FROM ubuntu:focal

RUN apt-get update -qqy
RUN apt-get upgrade -qqy
RUN apt-get install dumb-init
RUN apt-get install -y libssl-dev libgomp1
ADD ./redis-stack /var/cache/apt/redis-stack/
RUN mkdir -p /data/redis /data/redisinsight
RUN touch /.dockerenv

{% if docker_type == 'redis-stack-server' or docker_type == 'redis-stack-cluster'  %}
RUN dpkg -i /var/cache/apt/redis-stack/redis-stack-server*.deb
{% elif docker_type == 'redis-stack' %}
# RUN dpkg -i /var/cache/apt/redis-stack/redis-stack*.deb
RUN apt-get install -y libsecret-1-0
RUN dpkg -i /var/cache/apt/redis-stack/redis-stack-server*.deb
RUN dpkg -i /var/cache/apt/redis-stack/redisinsight*.deb
{% endif %}
RUN rm -rf /var/cache/apt

{% if docker_type == 'redis-stack-cluster' %}
COPY ./etc/scripts/create_cluster.sh /create_cluster.sh
RUN chmod +x /create_cluster.sh
{% else %}
COPY ./etc/scripts/entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh
{% endif %}

{% if docker_type == 'redis-stack-server' %}
EXPOSE 6379
{% elif docker_type == 'redis-stack-cluster' %}
EXPOSE 16379 16380 16381 16382 16383 16384
{% elif docker_type == 'redis-stack' %}
EXPOSE 6379 8001
{% endif %}

{% if docker_type == 'redis-stack' %}
COPY etc/envfiles/insight.docker.env /opt/redis-stack/share/redisinsight/.env
RUN chmod 0555 /opt/redis-stack/share/redisinsight/.env
{% endif %}

ENV REDISBLOOM_ARGS ""
ENV REDISEARCH_ARGS ""
ENV REDISJSON_ARGS ""
ENV REDISTIMESERIES_ARGS ""
ENV REDISGRAPH_ARGS ""
ENV REDIS_ARGS ""

{% if docker_type == 'redis-stack-cluster' %}
CMD ["/create_cluster.sh"]
{% else %}
CMD ["/entrypoint.sh"]
{% endif %}
